/*
Author: Connor Reardon
Date:4/21/16
Description: 

	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
	
	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	
	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

function fibo(){
	var first = 0;
	var second = 1;
	var sum = 1;
	var lst = []
	var total = 0;
	while (sum < 4000000){
		// i++;
		sum = first + second
		first = second
		second = sum
		if (sum % 2 === 0){
			total += sum
		}
	}
	return total;
}


console.log(fibo())
